### ISSUE TITLE
Install LTSP in Debian with Vagrant

### ISSUE THREAD

**Issue by d78ui98** [docker-scripts/dev--LTSP#34]
Will refer to here http://dashohoxha.fs.al/ltsp-pnp/
to install LTSP in debian `buster` with vagrant

**Comment by d78ui98** [comment]
I am able to install LTSP in debian `buster` and `stretch` release
But there are 2 issues with it-
- `buster` box is unable to mount `/vagrant`(working towards fixing this). So I tired `stretch`.
- I am unable to login from client in both these boxes. LTSP server is refusing connection and says public key denied.(working towards fixing this too)

**Comment by d78ui98** [comment]
@dashohoxha @akash0x53 
I have solved the first issue mentioned in the above comment. 
But I am having trouble solving the second issue. I followed every step from  http://dashohoxha.fs.al/ltsp-pnp/ and installed ltsp with vagrant on `buster`.
Able to boot from ltsp client too. But, I am unable to login. It says permission denied public key. 
I have made a small video of the problem - https://youtu.be/4ue23MVEd9g
I would need help here.

**Comment by dashohoxha** [comment]
@d78ui98 your video only proves that you have a problem.
If @akash0x53 wants to help you on this, he should be able to reproduce your problem. He cannot do this unless you share your code, and you cannot share your code without making first a pull request.

**Comment by d78ui98** [comment]
Okay, I will create a pull request.

**Comment by d78ui98** [comment]
one good news. I created an issue https://github.com/fujimakishouten/vagrant-boxes/issues/1 mentioning about problems with `buster` box and later provided the solution too. They were able to reproduce the issue and accepted my solution and wrote a wiki page about it

**Comment by dashohoxha** [comment]
Congratulations.

> I am unable to login from client in both these boxes. LTSP server is refusing connection and says public key denied.(working towards fixing this too)

If login works on `bionic` but does not work on `buster`, then you should try to find out what is different between these two. If you followed the same installation instructions (http://dashohoxha.fs.al/ltsp-pnp/) and installed the same packages (`ltsp-server` or `ltsp-server-standalone`), then what is different between these two packages? Are they the same version, or do they have the same content? How can we see what is different between a debian package and a ubuntu package?

What about the package `ldm-ubuntu-theme`, what did you install in debian instead of it? What display manager do you actually have on `buster`? I remember that at least one of the display managers of linux does not work well with ltsp for some reason. Maybe this is the problem that you have.

**Comment by dashohoxha** [comment]
Make sure that you have a display manager other than **mdm**: http://dashohoxha.fs.al/ltsp-pnp/#sec-6

**Comment by d78ui98** [comment]
Thank you :)

display manager used in `buster` is **lxde**. I think this is not a problem of ltsp packages. If that was the case than we wont be able to boot from the client. This is a problem with either vagrant box or the ssh config file. I closely looking at differences in both these boxes. Will find this issue soon. Just need some time.

**Comment by dashohoxha** [comment]
I wish that you solve it soon.
When you cannot login, it is usually a display manager problem.
From the video also it looks like that.
So, try to replace lxde with LightDM or something that is known to work.

**Comment by akash0x53** [comment]
To solve ssh problem install private key provided by vagrant into client. You can find these keys [here](https://github.com/hashicorp/vagrant/tree/master/keys).

**Comment by d78ui98** [comment]
Niceee... This has solved the issue :+1:

**Comment by d78ui98** [comment]
This solves the problem. But it is not a good solution from a security point of view. I figured out the mistake and fixed it.
