### ISSUE TITLE
Create provisioning scripts to start virtualbox LTSP server

### ISSUE THREAD

**Issue by d78ui98** [docker-scripts/dev--LTSP#5]
Writing a Vagrant script to automatically start up a standard VirtualBox LTSP server.

**Comment by dashohoxha** [comment]
For this you can start by taking as an example one of the projects that I asked you to install as an application task.

Then you need to study what are the command line configuration options of virtualbox, and how to use them on the Vagrantfile. These options are needed to set the network interface in bridged mode and promiscuous mode.

You also need to have a good knowledge of bash scripting, so you should finish as soon as possible the bash guides that I told you during the application period, if you have not finished them yet.

@d78ui98 (I am mentioning you, so that you get notified)

**Comment by dashohoxha** [comment]
You should also do the scripts for the debian:buster. Maybe you should create another task for that.

**Comment by d78ui98** [comment]
okay. I will do that.
